import { createAsyncThunk } from "@reduxjs/toolkit";
import axios from "axios";

// Async thunk for fetching API data
export const fetchData = createAsyncThunk(
  "api/fetchData",
  async (url: string) => {
    const response = await axios.get(url, {
      headers: {
        "application-id": 7,
        Authorization:
          "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoSW1DdEZEYTNGa2ZfQmFuZEFwNjZwOWpsVTFrclFfbGlHeVE4RkFMRTNnIn0.eyJleHAiOjE3MzAyMjgzNzUsImlhdCI6MTczMDE5MjM3NSwianRpIjoiM2FmYmUwYzQtMmE2YS00OTA5LTg0ZjEtNzYwODM3YTA5NGNjIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnByaW1yb3NlLmhlYWx0aC9yZWFsbXMvY2xpbmljIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjYzNWMxZGRmLWQxNjYtNDFiYi1iZGIyLTkzMWQ3MDM4ZjYyMSIsInR5cCI6IkJlYXJlciIsImF6cCI6Im1lZGljYWwtY29kaW5nIiwic2lkIjoiNGJlNjRiYjQtOGMyZS00NDY0LWJkYjAtOTE5NGUyNDQxZjcxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vYXBpLnRyaWxsaXVtLmhlYWx0aCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiQURNSU5JU1RSQVRPUiIsIkRFTU9HUkFQSElDUyIsImRlZmF1bHQtcm9sZXMtY2xpbmljIiwib2ZmbGluZV9hY2Nlc3MiLCJJTlRFUk5BTCIsIkVMSUdJQklMSVRZX1BPUlRBTCIsIlBSSU9SX0FVVEgiLCJBUl9NQU5BR0VSIiwidW1hX2F1dGhvcml6YXRpb24iLCJDT0RFUl9QT1JUQUwiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiY2xpbmljSWQiOjAsImlzQWRtaW5pc3RyYXRvckFjY2VzcyI6dHJ1ZSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiVmluZWV0aCBKb3NlcGgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ2aW5lZXRoIiwiZ2l2ZW5fbmFtZSI6IlZpbmVldGgiLCJ1c2VySWQiOjEyLCJmYW1pbHlfbmFtZSI6Ikpvc2VwaCJ9.aqKIcQOwylz5wnklKPpziR3Y46FQZdG2RfdwkoucLaoQwXfSpSxrTV7pTLhmpFXAQaiumnVqh8CQRkNJ9O82X7Y-gm_0lggbK7VSpKc6WUp1EpKeTqb-tEHG9U4khvmASJCb24tJt9odbZag1TPnLl-U9ok7ByyYpArHtoQ5_nqwEz8AQt1KcoEyRNYy7C43m-yfXWDLcdC3SqrV8S9zx3_TTDYCZP98Dz7RnPoWGWYVqGpXR2JIfstms7uCFn3drLpcy1VTrPcagwvfifoZpL6OW-b42DlEu4G2MybmeTZH3N-IV-NZDBuAPwoEVaAfz6mnTwnJ-fRZ8B5Fnn0_rQ",
      },
    });
    return response.data; // Adjust according to your API response
  }
);
